---
include:
  - board: nice_nano_v2
    shield: corne_tp_left nice_view_adapter nice_view_gem
    artifact-name: corne_tp_left
  - board: nice_nano_v2
    shield: corne_tp_right

  # Settings Reset firmware
  - board: nice_nano_v2
    shield: settings_reset
