---
include:
  - board: nice_nano_v2
    shield: corne_tp_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: corne_tp_right
    #snippet: studio-rpc-usb-uart

  # Alternative PINs firmware
  - board: nice_nano_v2
    shield: corne_tp_right
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DMOUSE_PS2_ALT_PINS
    artifact-name: corne_tp_right-nice_nano_v2-scl_D3_sda_D2-zmk

  # Settings Reset firmware
  - board: nice_nano_v2
    shield: settings_reset
